# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
      - dist: trusty
        github_packages:
          - r-lib/pkgdown
          - ropensci/rotemplate
      - r: release
        before_cache: Rscript -e 'remotes::install_cran("pkgdown");remotes::install_github("ropensci/rotemplate")'
        deploy:
          provider: script
          script: Rscript -e 'pkgdown::deploy_site_github()'
          skip_cleanup: true
      - r: devel

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

after_success:
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

