# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr
  - lionel-/vdiffr

after_success:
  - Rscript -e 'library(covr); codecov()'

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libfreetype6
